import Head from "next/head";
import { AboutSection } from "~/components/AboutSection";
import { CommunitySection } from "~/components/CommunitySection";
import { Footer } from "~/components/Footer";
import { Header } from "~/components/Header";
import { HeroSection } from "~/components/HeroSection";
import { StackSection } from "~/components/StackSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="container mx-auto px-4">
        <HeroSection />
        <AboutSection />
        <StackSection />
        <CommunitySection />
      </main>
      <Footer />
    </>
  );
}
